const MONITOREO_DATA = {
  "2025": [
    {
      "Provincia": "Tierra del Fuego",
      "URE N°": "8",
      "Trimestre": "2",
      "ID PLAN": "PM-FORESTO-INDUSTRIAL- POA1",
      "Fecha de monitoreo en campo": "2025-04-07",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Ricardo Vukasovic",
      "IF": "IF-2025-57988817-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": "Ajustar a Resol 427/2020_ Informar sobre modificaciones al destino de fondos",
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Jujuy",
      "URE N°": "1",
      "Trimestre": "2",
      "ID PLAN": "PM-0256-273-A/2013",
      "Fecha de monitoreo en campo": "2025-04-09",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Pláate Gerardo - Campos Christian",
      "IF": "IF-2025-39425648-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tierra del Fuego",
      "URE N°": "8",
      "Trimestre": "2",
      "ID PLAN": "PC-RUTAS DEL SUR",
      "Fecha de monitoreo en campo": "2025-04-09",
      "Estado": "Informe en elaboración",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Ricardo Vukasovic",
      "IF": "IF-2025-79066481-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Jujuy",
      "URE N°": "1",
      "Trimestre": "2",
      "ID PLAN": "PM-256-370/2015",
      "Fecha de monitoreo en campo": "2025-04-15",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Federico Mohr",
      "IF": "IF-2025-61384472-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Jujuy",
      "URE N°": "1",
      "Trimestre": "2",
      "ID PLAN": "PM-0256-319-B/2015",
      "Fecha de monitoreo en campo": "2025-04-16",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Federico Mohr",
      "IF": "IF-2025-61384227-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tucumán",
      "URE N°": "1",
      "Trimestre": "2",
      "ID PLAN": "TUC_PC2017-04_MAY25",
      "Fecha de monitoreo en campo": "2025-05-09",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Silvia Pacheco",
      "IF": "IF-2025-67899911-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tucumán",
      "URE N°": "1",
      "Trimestre": "2",
      "ID PLAN": "TUC_PC2016-5_MAY25",
      "Fecha de monitoreo en campo": "2025-05-09",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Silvia Pacheco",
      "IF": "IF-2025-67902167-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Misiones",
      "URE N°": "4",
      "Trimestre": "2",
      "ID PLAN": "13-PF-PM-228-20201- POA1-228-2021",
      "Fecha de monitoreo en campo": "2025-05-15",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Lucas Giraudo",
      "IF": "IF-2025-71110463-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": "Se observan oportunidades de mejorar el uso de los fondos de la ley si se reducen los tiempos en desembolsarlos al titular para ejecutar las actividades planificadas una vez presentado el PMS.",
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tierra del Fuego",
      "URE N°": "8",
      "Trimestre": "2",
      "ID PLAN": "PI-EA ROLITO",
      "Fecha de monitoreo en campo": "2025-05-17",
      "Estado": "Informe en elaboración",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Ricardo Vukasovic",
      "IF": "IF-2025-77104610-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tucumán",
      "URE N°": "1",
      "Trimestre": "2",
      "ID PLAN": "TUC_PC2017-05_MAY25",
      "Fecha de monitoreo en campo": "2025-05-30",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Silvia Pacheco",
      "IF": "IF-2025-67903272-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "2",
      "ID PLAN": "703-20-2017",
      "Fecha de monitoreo en campo": "2025-06-26",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Walter Cassino- Abel Gómez",
      "IF": "IF-2025-77033171-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "2",
      "ID PLAN": "EX-2021-01391974- -GDESDE-DB#MPR",
      "Fecha de monitoreo en campo": "2025-06-27",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Walter Cassino- Abel Gómez",
      "IF": "IF-2025-77032826-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "2",
      "ID PLAN": "684-20-2014",
      "Fecha de monitoreo en campo": "2025-06-30",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Walter Cassino- Abel Gómez",
      "IF": "IF-2025-77030222-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "2",
      "ID PLAN": "EX-2024-00819707- -GDESDE-DB#MPR",
      "Fecha de monitoreo en campo": "2025-06-30",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Walter Cassino- Abel Gómez",
      "IF": "IF-2025-77030540-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Formosa",
      "URE N°": "2",
      "Trimestre": "3",
      "ID PLAN": "A-0042- 2023",
      "Fecha de monitoreo en campo": "2025-08-10",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Carla Antonella Vega",
      "IF": "IF-2025-129750695-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Formosa",
      "URE N°": "2",
      "Trimestre": "3",
      "ID PLAN": "C-0080-2022",
      "Fecha de monitoreo en campo": "2025-08-11",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Carla Antonella Vega",
      "IF": "IF-2025-129746102-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Formosa",
      "URE N°": "2",
      "Trimestre": "3",
      "ID PLAN": "C-0081-2022",
      "Fecha de monitoreo en campo": "2025-08-12",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Carla Antonella Vega",
      "IF": "IF-2025-129752500-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Formosa",
      "URE N°": "2",
      "Trimestre": "3",
      "ID PLAN": "H-2206- 2024",
      "Fecha de monitoreo en campo": "2025-08-12",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Carla Antonella Vega",
      "IF": "IF-2025-129962341-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Formosa",
      "URE N°": "2",
      "Trimestre": "3",
      "ID PLAN": "H-2207-2024",
      "Fecha de monitoreo en campo": "2025-08-13",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Carla Antonella Vega",
      "IF": "IF-2025-129942730-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Jujuy",
      "URE N°": "1",
      "Trimestre": "3",
      "ID PLAN": "PM-1102-208-V/2019",
      "Fecha de monitoreo en campo": "2025-09-03",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Federico Mohr-Juan Pablo Martinez",
      "IF": "IF-2025-105311677-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": "Se utilizó kobo collect y vuelos de dron como apoyo técnico",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Jujuy",
      "URE N°": "1",
      "Trimestre": "3",
      "ID PLAN": "PM-1102-127-F/2020",
      "Fecha de monitoreo en campo": "2025-09-04",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Federico Mohr-Juan Pablo Martinez",
      "IF": "IF-2025-108140025-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": "Se utilizó kobo collect y vuelos de dron como apoyo técnico",
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "jujuy",
      "URE N°": "1",
      "Trimestre": "3",
      "ID PLAN": "PM-0256-341-F/2014",
      "Fecha de monitoreo en campo": "2025-09-04",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Federico Mohr-Juan Pablo Martinez",
      "IF": "IF-2025-108136991-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": "Se utilizó kobo collect y vuelos de dron como apoyo técnico",
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tucumán",
      "URE N°": "1",
      "Trimestre": "3",
      "ID PLAN": "TUC_PF2021-01_SET25",
      "Fecha de monitoreo en campo": "2025-09-11",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Silvia Pacheco",
      "IF": "IF-2025-108416388-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": "Se utilizó kobo collect",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tucumán",
      "URE N°": "1",
      "Trimestre": "3",
      "ID PLAN": "TUC_PF2021-13_SET25",
      "Fecha de monitoreo en campo": "2025-09-11",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Silvia Pacheco",
      "IF": "IF-2025-108418801-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": "Se utilizó kobo collect",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Jujuy",
      "URE N°": "1",
      "Trimestre": "3",
      "ID PLAN": "PMyC 1102-559-D/2023",
      "Fecha de monitoreo en campo": "2025-09-17",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Gerardo Pláate",
      "IF": "IF-2025-106152206-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Jujuy",
      "URE N°": "1",
      "Trimestre": "3",
      "ID PLAN": "PMyC 1102-597-D/2023",
      "Fecha de monitoreo en campo": "2025-09-17",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Gerardo Pláate",
      "IF": "IF-2025-106154590-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Jujuy",
      "URE N°": "1",
      "Trimestre": "3",
      "ID PLAN": "PMyC 1102-558-D/2023",
      "Fecha de monitoreo en campo": "2025-09-17",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Gerardo Pláate",
      "IF": "IF-2025-106156375-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Jujuy",
      "URE N°": "1",
      "Trimestre": "3",
      "ID PLAN": "PC-0257-47-C/2014",
      "Fecha de monitoreo en campo": "2025-09-18",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Gerardo Pláate",
      "IF": "IF-2025-106158238-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Chaco",
      "URE N°": "2",
      "Trimestre": "3",
      "ID PLAN": "PN2015/053",
      "Fecha de monitoreo en campo": "2025-09-19",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Sergio Torrez Ledesma",
      "IF": "IF-2025-108913653-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Chaco",
      "URE N°": "2",
      "Trimestre": "3",
      "ID PLAN": "PN2015/048",
      "Fecha de monitoreo en campo": "2025-09-19",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Sergio Torrez Ledesma",
      "IF": "IF-2025-108913369-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tucumán",
      "URE N°": "1",
      "Trimestre": "3",
      "ID PLAN": "TUC_PF2021-08_SET25",
      "Fecha de monitoreo en campo": "2025-09-23",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Silvia Pacheco",
      "IF": "IF-2025-108420832-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": "Se utilizó kobo collect",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Chubut",
      "URE N°": "7",
      "Trimestre": "3",
      "ID PLAN": "CU-PC-37-2017-POA-03",
      "Fecha de monitoreo en campo": "2025-09-26",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Nadia Griffiths",
      "IF": "IF-2025-113608751-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": "se utilizó Kobo",
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Misiones",
      "URE N°": "4",
      "Trimestre": "4",
      "ID PLAN": "13-PC-02017-2022",
      "Fecha de monitoreo en campo": "2025-10-08",
      "Estado": "Finzalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Marisol Morales y Lucas Giraudo",
      "IF": "IF-2025-132991787-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Misiones",
      "URE N°": "4",
      "Trimestre": "4",
      "ID PLAN": "13-PC-02117-2021",
      "Fecha de monitoreo en campo": "2025-10-08",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Marisol Morales y Lucas Giraudo",
      "IF": "IF-2025-132993395-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tierra del Fuego",
      "URE N°": "8",
      "Trimestre": "4",
      "ID PLAN": "PM-PARQUE INDUSTRIAL-POA1",
      "Fecha de monitoreo en campo": "2025-10-08",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": null,
      "Tecnico/s que fueron al campo": "Ricardo Vukasovic",
      "IF": "IF-2025-118356867-APN-DBN%JGM.pdf",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Córdoba",
      "URE N°": "5",
      "Trimestre": "4",
      "ID PLAN": "0517-026088/PC23",
      "Fecha de monitoreo en campo": "2025-10-13",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Ana Contreras y Maria Jose Del Bó",
      "IF": "IF-2025-120776830-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "en elaboracion",
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Córdoba",
      "URE N°": "5",
      "Trimestre": "4",
      "ID PLAN": "0517-021533/PC19",
      "Fecha de monitoreo en campo": "2025-10-13",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Ana Contreras y Maria Jose Del Bó",
      "IF": "IF-2025-120778209-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "en elaboracion",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Chubut",
      "URE N°": "7",
      "Trimestre": "4",
      "ID PLAN": "CU-PMyC-21-2022",
      "Fecha de monitoreo en campo": "2025-10-14",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "Si",
      "Tecnico/s que fueron al campo": "Nadia Grifiths y Lara Haure",
      "IF": "IF-2025-117922007-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Córdoba",
      "URE N°": "5",
      "Trimestre": "4",
      "ID PLAN": "0517-016465/PC22",
      "Fecha de monitoreo en campo": "2025-10-16",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Ana Contreras y Maria Jose Del Bó",
      "IF": "IF-2025-120777747-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "en elaboracion",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Córdoba",
      "URE N°": "5",
      "Trimestre": "4",
      "ID PLAN": "0517-024296/PC21",
      "Fecha de monitoreo en campo": "2025-10-16",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Ana Contreras y Maria Jose Del Bó",
      "IF": "IF-2025-120777203-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "en elaboracion",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Misiones",
      "URE N°": "4",
      "Trimestre": "4",
      "ID PLAN": "13-PF-PM-219-2021",
      "Fecha de monitoreo en campo": "2025-10-18",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Marisol Morales y Lucas Giraudo",
      "IF": "IF-2025-137843153-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Misiones",
      "URE N°": "4",
      "Trimestre": "4",
      "ID PLAN": "13-PF-PM-237-2022",
      "Fecha de monitoreo en campo": "2025-10-18",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Marisol Morales y Lucas Giraudo",
      "IF": "IF-2025-137842581-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santa Cruz",
      "URE N°": "8",
      "Trimestre": "4",
      "ID PLAN": "07-PC-2019",
      "Fecha de monitoreo en campo": "2025-10-18",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": null,
      "Tecnico/s que fueron al campo": "Ricardo Vukasovic",
      "IF": "IF-2025-118354710-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santa Cruz",
      "URE N°": "8",
      "Trimestre": "4",
      "ID PLAN": "03-PF-2019",
      "Fecha de monitoreo en campo": "2025-10-19",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": null,
      "Tecnico/s que fueron al campo": "Ricardo Vukasovic",
      "IF": "IF-2025-118353910-APN-DBN%JGM.pdf",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Córdoba",
      "URE N°": "5",
      "Trimestre": "4",
      "ID PLAN": "0517-020342/PC16",
      "Fecha de monitoreo en campo": "2025-10-21",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "María José Del Bó",
      "IF": "IF-2025-120924615-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "en elaboracion",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Chubut",
      "URE N°": "7",
      "Trimestre": "4",
      "ID PLAN": "CU-PM-76-2017",
      "Fecha de monitoreo en campo": "2025-10-24",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Nadia Grifiths y Jessica Arre",
      "IF": "IF-2025-136621528-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "Se recomienda analizar la concordancia entre las actividades planificadas y el contexto territorial, considerando la posible expansión urbana en la zona en el mediano plazo. Dado que se trata de un área Fiscalización Plan – UREF7 potencialmente susceptible a procesos de loteo en la próxima década, las acciones de restauración propuestas podrían verse comprometidas o incluso revertidas, afectando su sostenibilidad a largo plazo.",
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Neuquén",
      "URE N°": "7",
      "Trimestre": "4",
      "ID PLAN": "NQN_PC_001_2013 POA 4",
      "Fecha de monitoreo en campo": "2025-11-04",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Silvia Castañeda",
      "IF": "IF-2025-131460216-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "Readecuación de planes institucioneles",
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "Si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Neuquén",
      "URE N°": "7",
      "Trimestre": "4",
      "ID PLAN": "NQN_PC_098_2022_POA 1",
      "Fecha de monitoreo en campo": "2025-11-05",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "Si",
      "Tecnico/s que fueron al campo": "Silvia Castañeda",
      "IF": "IF-2025-131464873-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "Si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Neuquén",
      "URE N°": "7",
      "Trimestre": "4",
      "ID PLAN": "NQN_PC_027_2018_POA1",
      "Fecha de monitoreo en campo": "2025-11-05",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "Si",
      "Tecnico/s que fueron al campo": "Silvia Castañeda",
      "IF": "IF-2025-131466832-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "Si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Río Negro",
      "URE N°": "7",
      "Trimestre": "4",
      "ID PLAN": "PM_2022_LOSTRA_EL_VENTISQUERO",
      "Fecha de monitoreo en campo": "2025-11-19",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "Si",
      "Tecnico/s que fueron al campo": "Silvia Castañeda",
      "IF": "IF-2025-143506362-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "Sin observaciones",
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Río Negro",
      "URE N°": "7",
      "Trimestre": "4",
      "ID PLAN": "PM_2022_SOSA_EL_MANGRULLO",
      "Fecha de monitoreo en campo": "2025-11-19",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Silvia Castañeda",
      "IF": "IF-2025-143356490-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "Sin observaciones",
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Salta",
      "URE N°": "1",
      "Trimestre": "4",
      "ID PLAN": "PM-65542/2014-7",
      "Fecha de monitoreo en campo": "2025-11-20",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Federico Mohr-Christian Campos - Marcelo Perez",
      "IF": "IF-2025-134792519-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "Se realizó vuelo con dron- se calcularon índices en base a muestreo de aves e IPH",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Salta",
      "URE N°": "1",
      "Trimestre": "4",
      "ID PLAN": "PM-34938/2013-6",
      "Fecha de monitoreo en campo": "2025-11-20",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Federico Mohr - Marcelo Perez",
      "IF": "IF-2025-134790510-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "Se  calcularon índices en base a muestreo de aves e IPH",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "La Pampa",
      "URE N°": "5",
      "Trimestre": "4",
      "ID PLAN": "13922/22-PM",
      "Fecha de monitoreo en campo": "2025-11-20",
      "Estado": null,
      "Alcanzado por SAT?": null,
      "Tecnico/s que fueron al campo": "Silvio Quarleri",
      "IF": null,
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "NO",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "La Pampa",
      "URE N°": "5",
      "Trimestre": "4",
      "ID PLAN": "2620/14-PM",
      "Fecha de monitoreo en campo": "2025-11-20",
      "Estado": null,
      "Alcanzado por SAT?": null,
      "Tecnico/s que fueron al campo": "Silvio Quarleri",
      "IF": null,
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "NO",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Salta",
      "URE N°": "1",
      "Trimestre": "4",
      "ID PLAN": "PM-225856/2012-6",
      "Fecha de monitoreo en campo": "2025-11-26",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Federico Mohr - Marcelo Perez",
      "IF": "IF-2025-134791028-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "Se realizó vuelo con dron- se calcularon índices en base a muestreo de aves e IPH",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Salta",
      "URE N°": "1",
      "Trimestre": "4",
      "ID PLAN": "PM-225859/2012-5",
      "Fecha de monitoreo en campo": "2025-11-26",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Federico Mohr - Marcelo Perez",
      "IF": "IF-2025-134791479-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "Se  calcularon índices en base a muestreo de aves e IPH",
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": null,
      "URE N°": "2",
      "Trimestre": "4",
      "ID PLAN": "PN 2023/13288",
      "Fecha de monitoreo en campo": "2025-11-20",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Sergio Torrez Ledesma",
      "IF": "IF-2025-143803237-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Chaco",
      "URE N°": "2",
      "Trimestre": "4",
      "ID PLAN": "PN 2023/13139",
      "Fecha de monitoreo en campo": "2025-11-20",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Sergio Torrez Ledesma",
      "IF": "IF-2025-143846100-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Chaco",
      "URE N°": "2",
      "Trimestre": "4",
      "ID PLAN": "PN2019/002",
      "Fecha de monitoreo en campo": "2025-11-20",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Sergio Torrez Ledesma",
      "IF": "IF-2025-143864544-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "NO",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "4",
      "ID PLAN": "EX-2021-01410302- -GDESDE-DB#MPR",
      "Fecha de monitoreo en campo": "2025-12-15",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Walter Cassino- Abel Gómez",
      "IF": "IF-2026-01029349-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "4",
      "ID PLAN": "EX-2021-01410201- -GDESDE-DB#MPR",
      "Fecha de monitoreo en campo": "2025-12-15",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Walter Cassino- Abel Gómez",
      "IF": "IF-2026-01029510-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "4",
      "ID PLAN": "EX-2021-01401051-   -GDESDE-DB#MPR",
      "Fecha de monitoreo en campo": "2025-12-17",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Walter Cassino- Abel Gómez",
      "IF": "IF-2026-01029139-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": null,
      "URE N°": "2",
      "Trimestre": "4",
      "ID PLAN": "EX-2021-01406356- -GDESDE-DB#MPR",
      "Fecha de monitoreo en campo": "2025-12-17",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "NO",
      "Tecnico/s que fueron al campo": "Walter Cassino- Abel Gómez",
      "IF": "IF-2026-01029762-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "4",
      "ID PLAN": "EX-2021-01431197-   -GDESDE-DB#MPR",
      "Fecha de monitoreo en campo": "2025-12-18",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Walter Cassino- Abel Gómez",
      "IF": "IF-2026-01028904-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": "SI",
      "Otro espacio de guardado": null
    }
  ],
  "2026": [
    {
      "Provincia": "Santa Fe",
      "URE N°": "3",
      "Trimestre": "2",
      "ID PLAN": "02101-0021092-6",
      "ID POA": null,
      "Fecha de monitoreo en campo": "2026-05-26",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Julieta Carbaja- Victoria del Sastre- Mercedes Mierez",
      "IF": "IF-2026-54915216-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "si",
      "Subido IF a carpeta compartida Bosques": "sin acceso",
      "Otro espacio de guardado": "Drive de la URE"
    },
    {
      "Provincia": "Santa Fe",
      "URE N°": "3",
      "Trimestre": "2",
      "ID PLAN": "02101-0028742-3",
      "ID POA": null,
      "Fecha de monitoreo en campo": "2026-05-26",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "si",
      "Tecnico/s que fueron al campo": "Julieta Carbajal- Victoria del Sastre- Mercedes Mierez",
      "IF": "F-2026-56987530-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "si",
      "Subido IF a carpeta compartida Bosques": "sin acceso",
      "Otro espacio de guardado": "Drive de la URE"
    },
    {
      "Provincia": "Santa Fe",
      "URE N°": "3",
      "Trimestre": "2",
      "ID PLAN": "02101-0034076-6",
      "ID POA": null,
      "Fecha de monitoreo en campo": "2026-05-27",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "no",
      "Tecnico/s que fueron al campo": "Julieta Carbajal- Victoria del Sastre- Mercedes Mierez",
      "IF": "IF-2026-56989470-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "si",
      "Subido IF a carpeta compartida Bosques": "sin acceso",
      "Otro espacio de guardado": "Drive de la URE"
    },
    {
      "Provincia": "Santa Fe",
      "URE N°": "3",
      "Trimestre": "2",
      "ID PLAN": "210100351603",
      "ID POA": null,
      "Fecha de monitoreo en campo": "2026-05-27",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "si",
      "Tecnico/s que fueron al campo": "Julieta Carbaja- Victoria del Sastre- Mercedes Mierez",
      "IF": "IF-2026-56989688-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "si",
      "Subido IF a carpeta compartida Bosques": "sin acceso",
      "Otro espacio de guardado": "Drive de la URE"
    },
    {
      "Provincia": "Córdoba",
      "URE N°": "5",
      "Trimestre": "2",
      "ID PLAN": "0517-025736/PC21",
      "ID POA": "0517-025736/PC21; 0517-025736/PC22;0517-025736/PC23 y 0517-025736/PC24",
      "Fecha de monitoreo en campo": "2026-05-21",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "Si",
      "Tecnico/s que fueron al campo": "María José del Bo-Ana Marina Contreras",
      "IF": "IF-2026-59182226-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "si",
      "Subido IF a carpeta compartida Bosques": "si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Córdoba",
      "URE N°": "5",
      "Trimestre": "2",
      "ID PLAN": "0517-026711/PC23",
      "ID POA": "0517-026711/PC23  0517-026711/PC24",
      "Fecha de monitoreo en campo": "2026-05-28",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "María José del Bo-Ana Marina Contreras",
      "IF": "IF-2026-59182593-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "si",
      "Subido IF a carpeta compartida Bosques": "si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tucumán",
      "URE N°": "1",
      "Trimestre": "2",
      "ID PLAN": "2010/05",
      "ID POA": "POA8-2010/05 y POA9-2010/05",
      "Fecha de monitoreo en campo": "2026-06-01",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Federico Mohr, Silvia Pacheco",
      "IF": "IF-2026-67983526-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "si",
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tucumán",
      "URE N°": "1",
      "Trimestre": "2",
      "ID PLAN": "2013/22",
      "ID POA": "POA 5 2013/22 y POA6 2013/22",
      "Fecha de monitoreo en campo": "2026-06-02",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "Si",
      "Tecnico/s que fueron al campo": "Federico Mohr, Silvia Pacheco",
      "IF": "IF-2026-67983723-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "si",
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tucumán",
      "URE N°": "1",
      "Trimestre": "2",
      "ID PLAN": "2013/06",
      "ID POA": "POA5-2013/06 y POA6-2013/06",
      "Fecha de monitoreo en campo": "2026-06-02",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Federico Mohr, Silvia Pacheco",
      "IF": "IF-2026-67983855-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "si",
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Entre Ríos",
      "URE N°": "3",
      "Trimestre": "2",
      "ID PLAN": "ER_PM_Huck",
      "ID POA": null,
      "Fecha de monitoreo en campo": "2026-05-12",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Victoria del Sastre",
      "IF": "IF-2026-66416035-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": "Mejorar la carga en el RNP",
      "Cargado IF en SIIF": null,
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Entre Ríos",
      "URE N°": "3",
      "Trimestre": "2",
      "ID PLAN": "ER2022_PF_Soloaga",
      "ID POA": null,
      "Fecha de monitoreo en campo": "2026-05-13",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "si",
      "Tecnico/s que fueron al campo": "Victoria del Sastre",
      "IF": "IF-2026-66416171-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": "Mejorar la carga en el RNP",
      "Cargado IF en SIIF": null,
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santa Cruz",
      "URE N°": "8",
      "Trimestre": "2",
      "ID PLAN": "04-PM-2022",
      "ID POA": "04-PC-2022",
      "Fecha de monitoreo en campo": "2026-05-07",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Ricardo Vukasovic",
      "IF": "IF-2026-52311205-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "Si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santa Cruz",
      "URE N°": "8",
      "Trimestre": "2",
      "ID PLAN": "05-PC-2021",
      "ID POA": "05-PM-2021",
      "Fecha de monitoreo en campo": "2026-05-07",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "Si",
      "Tecnico/s que fueron al campo": "Ricardo Vukasovic",
      "IF": "IF-2026-57406203-APN-DBN%JGM_PREV CONTROL INC_05-PM-POA1",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "Si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santa Cruz",
      "URE N°": "8",
      "Trimestre": "2",
      "ID PLAN": "06-PM-2021",
      "ID POA": "06-PM-2021",
      "Fecha de monitoreo en campo": "2026-05-06",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "Si",
      "Tecnico/s que fueron al campo": "Ricardo Vukasovic",
      "IF": "IF-2026-50456870-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "Si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Neuquén",
      "URE N°": "7",
      "Trimestre": "1",
      "ID PLAN": "NQN_PI_099_2022",
      "ID POA": "NQN_PI_099_2022_POA 1\nNQN_PI_099_2022_POA 2_2023",
      "Fecha de monitoreo en campo": "2026-03-19",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Silvia Castañeda",
      "IF": "IF-2026-42007717-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": null,
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Neuquén",
      "URE N°": "7",
      "Trimestre": "1",
      "ID PLAN": "NQN_PI_110_2022",
      "ID POA": "NQN_PI_110_2023_POA 1",
      "Fecha de monitoreo en campo": "2026-03-20",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Silvia Castañeda",
      "IF": "IF-2026-37714980-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": null,
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Tierra del Fuego",
      "URE N°": "8",
      "Trimestre": "2",
      "ID PLAN": "PIC-RAFAELA ISHTON",
      "ID POA": null,
      "Fecha de monitoreo en campo": "2026-04-28",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "Si",
      "Tecnico/s que fueron al campo": "Ricardo Vukasovic",
      "IF": "IF-2026-57178341-APN-DBN%JGM_MONIT_POA1",
      "Observaciones relevantes para una devolución al ALA": "Monitoreo parcial se continuará en primavera",
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "Si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "2",
      "ID PLAN": "EX2023-10395507--GDESDE-DB#MPR",
      "ID POA": null,
      "Fecha de monitoreo en campo": "2026-06-18",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Walter Cassino, Abel Gomez",
      "IF": "IF-2026-66449745-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "Si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "2",
      "ID PLAN": "EX2022-04118973--GDESDE-DB#MPR",
      "ID POA": null,
      "Fecha de monitoreo en campo": "2026-06-18",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Walter Cassino, Abel Gomez",
      "IF": "IF-2026-66449659-APN-DBN#JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "Si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "Santiago del Estero",
      "URE N°": "2",
      "Trimestre": "2",
      "ID PLAN": "ID: 1045-20- 2014 POA:EX2022-04110304--GDESDE-DB#MPR",
      "ID POA": null,
      "Fecha de monitoreo en campo": "2026-06-19",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Walter Cassino, Abel Gomez",
      "IF": "IF-2026-66449839-APN-DBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": "Si",
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "San Juan",
      "URE N°": "6",
      "Trimestre": "2",
      "ID PLAN": "1300-308-25-PF",
      "ID POA": "1300-308-25-PF_POA 1_2023",
      "Fecha de monitoreo en campo": "2026-07-13",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Magali Taurian, Hidalgo Caballero Mariano Lucio",
      "IF": "IF-2026-85434616-APN-CBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "San Juan",
      "URE N°": "6",
      "Trimestre": "2",
      "ID PLAN": "1300-0404-13-PM",
      "ID POA": "1300-0404-13-PM_POA_10_2023",
      "Fecha de monitoreo en campo": "2026-07-14",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "SI",
      "Tecnico/s que fueron al campo": "Magali Taurian, Hidalgo Caballero Mariano Lucio",
      "IF": "IF-2026-85390243-APN-CBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "San Juan",
      "URE N°": "6",
      "Trimestre": "2",
      "ID PLAN": "1300-1419-12-PM",
      "ID POA": "1300-1419-12-PM_POA_8_2023",
      "Fecha de monitoreo en campo": "2026-07-14",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Magali Taurian, Hidalgo Caballero Mariano Lucio",
      "IF": "IF-2026-85388858-APN-CBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "Si",
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    },
    {
      "Provincia": "San Juan",
      "URE N°": "6",
      "Trimestre": "2",
      "ID PLAN": "1300-2359-11-PM",
      "ID POA": "1300-2359-11-PM_POA_3_2023",
      "Fecha de monitoreo en campo": "2026-07-15",
      "Estado": "Finalizado",
      "Alcanzado por SAT?": "No",
      "Tecnico/s que fueron al campo": "Magali Taurian, Hidalgo Caballero Mariano Lucio",
      "IF": "IF-2026-85389681-APN-CBN%JGM",
      "Observaciones relevantes para una devolución al ALA": null,
      "Cargado IF en SIIF": "SI",
      "Subido IF a carpeta compartida Bosques": null,
      "Otro espacio de guardado": null
    }
  ]
};
